/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import DAO.Nhanvien;
import DAO.NhanvienDAO;
import Tools.Dialog;
import Tools.Tienich;

/**
 *
 * @author Chu Ai Duc
 */
public class formChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form formChangePassword
     */
    NhanvienDAO dao=new NhanvienDAO();
    public formChangePassword() {
        initComponents();
        setNhanvien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblNhanvien = new javax.swing.JLabel();
        txtRenew = new javax.swing.JPasswordField();
        txtOld = new javax.swing.JPasswordField();
        txtNew = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Mật khẩu cũ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 90, 90, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Mật khẩu mới");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 160, 90, 19);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Xác nhận mật khẩu");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 230, 128, 19);

        jButton1.setText("Đổi mật khẩu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(330, 290, 130, 40);

        lblNhanvien.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblNhanvien.setText("Null");
        jPanel1.add(lblNhanvien);
        lblNhanvien.setBounds(100, 40, 320, 20);
        jPanel1.add(txtRenew);
        txtRenew.setBounds(210, 220, 230, 30);
        jPanel1.add(txtOld);
        txtOld.setBounds(210, 80, 230, 30);
        jPanel1.add(txtNew);
        txtNew.setBounds(210, 150, 230, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            String password = new String(txtOld.getPassword());
            String password1 = new String(txtNew.getPassword());
            String password2 = new String(txtRenew.getPassword());
            if(!password.equals(Tienich.user.getMatkhau())){
                Dialog.ThongBao(this, "Mật khẩu cũ không đúng");
                return;
            }
            if (password1.equals(password2)) {
                Nhanvien newnv=Tienich.user;
                newnv.setMatkhau(password1);
                int x = dao.updateToDB(newnv);
                if (x != 0) {
                    Tienich.writeQR(newnv.getManv(), newnv.getMatkhau());
                    formInfo.doimatkhau=true;
                    Dialog.ThongBao(this,"Đổi mật khẩu thành công");
                    this.dispose();
                } else {
                    Dialog.ThongBao(this, "Không thành công");
                }
            } else {
                Dialog.ThongBao(this, "Xác nhận mật khẩu sai");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formChangePassword().setVisible(true);
            }
        });
    }
    public void setNhanvien(){
        if(Tienich.user!=null){
            lblNhanvien.setText(Tienich.user.getHoten());
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNhanvien;
    private javax.swing.JPasswordField txtNew;
    private javax.swing.JPasswordField txtOld;
    private javax.swing.JPasswordField txtRenew;
    // End of variables declaration//GEN-END:variables
}
