/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import DAO.Nhanvien;
import DAO.NhanvienDAO;
import Tools.Dialog;
import Tools.Tienich;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Chu Ai Duc
 */
public class formInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form formInfo
     */
    NhanvienDAO dao = new NhanvienDAO();
    static boolean doimatkhau = false;

    public formInfo() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        fillnv();
    }

    public void fillnv() {
        try {
            dao.reLoad();
            Nhanvien nv = dao.getFull(Tienich.user.getManv());
            txtManv.setText(nv.getManv());
            txtHoten.setText(nv.getHoten());
            txtSDT.setText(nv.getSdt());
            txtDiachi.setText(nv.getDiachi());
            if (nv.isVaitro()) {
                txtVaitro.setText("Admin");
            }
            if (nv.isGt()) {
                gioitinh.setText("Nữ");
            } else {
                gioitinh.setText("Nam");
            }
            QRCODE.setIcon(Tienich.readQR(nv.getQRCODE()));
        } catch (Exception e) {
            Dialog.ThongBao(this, "Kết nối database hỏng");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        QRCODE = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtVaitro = new javax.swing.JLabel();
        txtManv = new javax.swing.JLabel();
        txtHoten = new javax.swing.JLabel();
        txtSDT = new javax.swing.JLabel();
        txtDiachi = new javax.swing.JLabel();
        gioitinh = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Mã nhân viên:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Họ và tên:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Số điện thoại:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Địa chỉ:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Giới tính:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("Vai trò:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("THÔNG TIN CỦA BẠN");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));
        jPanel1.add(QRCODE, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 350, 350));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton1.setText("Đổi mật khẩu cá nhân");
        jButton1.setBorder(null);
        jButton1.setPreferredSize(new java.awt.Dimension(140, 35));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 230, 40));

        txtVaitro.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtVaitro.setText("Nhân viên");
        jPanel1.add(txtVaitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        txtManv.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtManv.setText("jLabel9");
        jPanel1.add(txtManv, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        txtHoten.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtHoten.setText("jLabel10");
        jPanel1.add(txtHoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        txtSDT.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtSDT.setText("jLabel11");
        jPanel1.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        txtDiachi.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtDiachi.setText("txtDiachi");
        jPanel1.add(txtDiachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        gioitinh.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        gioitinh.setText("jLabel13");
        jPanel1.add(gioitinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        formChangePassword newform = new formChangePassword();
        newform.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        newform.setLocationRelativeTo(null);
        newform.setVisible(true);
        new Thread() {
            @Override
            public void run() {
                formInfo.doimatkhau=false;
                while (true) {
                    System.out.println("chay thread");
                    if(doimatkhau){
                            fillnv();
                            System.out.println("chay xong fill");
                            break;
                        }
                    if(!newform.isShowing()){
                        System.out.println(doimatkhau);
                        fillnv();
                        System.out.println("Ngat thread");
                        break;
                    }
                }
            }
        }.start();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel QRCODE;
    private javax.swing.JLabel gioitinh;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtDiachi;
    private javax.swing.JLabel txtHoten;
    private javax.swing.JLabel txtManv;
    private javax.swing.JLabel txtSDT;
    private javax.swing.JLabel txtVaitro;
    // End of variables declaration//GEN-END:variables
}
