/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import DAO.Khachhang;
import DAO.KhachhangDAO;
import Tools.Dialog;
import Tools.Kiemthu;
import Tools.Tienich;
import java.awt.Font;
import java.util.ArrayList;
import javafx.scene.paint.Color;
import javax.swing.JDesktopPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chu Ai Duc
 */
public class formKH extends javax.swing.JInternalFrame implements Kiemthu {

    KhachhangDAO dao = new KhachhangDAO();
    DefaultTableModel model;

    /**
     * Creates new form formNV
     */
    public formKH() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        tblKH.getTableHeader().setOpaque(false);
        tblKH.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 13));
        tblKH.getTableHeader().setBackground(new java.awt.Color(32, 136, 203));
        tblKH.getTableHeader().setForeground(new java.awt.Color(255, 255, 255));
        dao.reLoad();
        loadData();
        checkNew();
        
    }

    public void loadData() {
        try {
            dao.reLoad();
            ArrayList<Khachhang> list = dao.laydanhsach();
            model = (DefaultTableModel) tblKH.getModel();
            model.setRowCount(0);
            for (int i = 0; i < list.size(); i++) {
                model.addRow(new Object[]{list.get(i).getMakh(),
                    list.get(i).getHoten(),
                    gioitinh(list.get(i).isGt()),
                    list.get(i).getDiachi(),
                    list.get(i).getSdt(),
                    Tienich.FixNgayDK(list.get(i).getNgaydk())
                });
            }
        } catch (Exception e) {
            Dialog.ThongBao(this, "Ket noi Database That bai");
        }
    }

    public void checkNew() {
        txtMaKH.setText("");
        txtHoten.setText("");
        cboGioitinh.setSelectedIndex(0);
        txtSDT.setText("");
        txtDiachi.setText("");
        txtsearch.setText("");
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        btnAdd.setEnabled(true);
        txtMaKH.setEnabled(true);
    }

    public String gioitinh(boolean i) {
        if (i) {
            return "Nữ";
        } else {
            return "Nam";
        }
    }

    public boolean getGTDB(int x) {
        if (x == 1) {
            return true;
        } else {
            return false;
        }
    }

    public int returnIdx(boolean boo) {
        if (boo) {
            return 1;
        } else {
            return 0;
        }
    }

    public int insert() {
        String makh = txtMaKH.getText();
        System.out.println(makh);
        String tenkh = txtHoten.getText();
        System.out.println(tenkh);
        int gt = cboGioitinh.getSelectedIndex();
        System.out.println(gt);
        String sdt = txtSDT.getText();
        System.out.println(sdt);
        String diachi = txtDiachi.getText();
        System.out.println(diachi);
        Khachhang kh = new Khachhang(makh, tenkh, getGTDB(gt), diachi, sdt, Tienich.getNgayDK());
        return dao.addToDB(kh);
    }

    public int update() {
        String makh = txtMaKH.getText();
        String tenkh = txtHoten.getText();
        int gt = cboGioitinh.getSelectedIndex();
        String sdt = txtSDT.getText();
        String diachi = txtDiachi.getText();
        Khachhang kh = new Khachhang(makh, tenkh, getGTDB(gt), diachi, sdt, Tienich.getNgayDK());
        return dao.updateToDB(kh);
    }

    public int delete() {
        String makh = txtMaKH.getText();
        Khachhang newkh = dao.find(makh);
        return dao.deleteFromDB(newkh);
    }

    public ArrayList<Khachhang> search() {
        ArrayList<Khachhang> ketquatimkiem = new ArrayList<>();
        String value = txtsearch.getText().trim().toUpperCase();
        dao.reLoad();
        ArrayList<Khachhang> ds = dao.laydanhsach();
        for (int i = 0; i < ds.size(); i++) {
            if (ds.get(i).getMakh().toUpperCase().contains(value) | ds.get(i).getHoten().toUpperCase().contains(value) | ds.get(i).getDiachi().toUpperCase().contains(value)
                    | ds.get(i).getSdt().toUpperCase().contains(value)) {

                ketquatimkiem.add(ds.get(i));
            }
        }
        return ketquatimkiem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtsearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        txtHoten = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKH = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtDiachi = new javax.swing.JTextField();
        cboGioitinh = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnAdd1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Quản lý nhân viên");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(782, 495));
        jPanel1.setPreferredSize(new java.awt.Dimension(865, 560));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtsearch.setBackground(new java.awt.Color(0,0,0,0));
        txtsearch.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtsearch.setForeground(new java.awt.Color(255, 255, 204));
        txtsearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtsearch.setCaretColor(new java.awt.Color(255, 255, 255));
        txtsearch.setOpaque(false);
        txtsearch.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel1.add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, 35));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Họ và tên");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mã khách hàng");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Giới tính");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Số điện thoại");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Địa chỉ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        txtMaKH.setBackground(new java.awt.Color(0,0,0,0));
        txtMaKH.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtMaKH.setForeground(new java.awt.Color(255, 255, 204));
        txtMaKH.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMaKH.setBorder(null);
        txtMaKH.setCaretColor(new java.awt.Color(255, 255, 255));
        txtMaKH.setOpaque(false);
        jPanel1.add(txtMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 200, 35));

        txtHoten.setBackground(new java.awt.Color(0,0,0,0));
        txtHoten.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtHoten.setForeground(new java.awt.Color(255, 255, 204));
        txtHoten.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHoten.setBorder(null);
        txtHoten.setCaretColor(new java.awt.Color(255, 255, 255));
        txtHoten.setOpaque(false);
        jPanel1.add(txtHoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 200, 35));

        txtSDT.setBackground(new java.awt.Color(0,0,0,0));
        txtSDT.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtSDT.setForeground(new java.awt.Color(255, 255, 204));
        txtSDT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSDT.setBorder(null);
        txtSDT.setCaretColor(new java.awt.Color(255, 255, 255));
        txtSDT.setOpaque(false);
        jPanel1.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 200, 35));

        tblKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Họ và tên", "Giới tính", "Địa chỉ", "Điện thoại", "NgayDK"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKH.setFocusable(false);
        tblKH.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblKH.setRowHeight(30);
        tblKH.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tblKH.setShowVerticalLines(false);
        tblKH.getTableHeader().setReorderingAllowed(false);
        tblKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKHMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKH);
        if (tblKH.getColumnModel().getColumnCount() > 0) {
            tblKH.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblKH.getColumnModel().getColumn(2).setPreferredWidth(40);
            tblKH.getColumnModel().getColumn(3).setPreferredWidth(80);
            tblKH.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 770, 190));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Danh sách khách hàng");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        txtDiachi.setBackground(new java.awt.Color(0,0,0,0));
        txtDiachi.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtDiachi.setForeground(new java.awt.Color(255, 255, 204));
        txtDiachi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiachi.setBorder(null);
        txtDiachi.setCaretColor(new java.awt.Color(255, 255, 255));
        txtDiachi.setOpaque(false);
        jPanel1.add(txtDiachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 260, 35));

        cboGioitinh.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cboGioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        jPanel1.add(cboGioitinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        btnSearch.setBackground(new java.awt.Color(255, 204, 204));
        btnSearch.setText("Tìm");
        btnSearch.setBorder(null);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnSearch.setMargin(new java.awt.Insets(5, 10, 5, 10));
        btnSearch.setPreferredSize(new java.awt.Dimension(80, 40));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 83, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 200, 1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 200, 1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 260, 1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 200, 1));

        btnAdd.setBackground(new java.awt.Color(204, 204, 255));
        btnAdd.setText("Thêm");
        btnAdd.setBorder(null);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAdd.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnAdd.setPreferredSize(new java.awt.Dimension(80, 40));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(204, 204, 255));
        btnUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnUpdate.setLabel("Cập nhật");
        btnUpdate.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnUpdate.setPreferredSize(new java.awt.Dimension(80, 40));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 90, -1));

        btnDelete.setBackground(new java.awt.Color(204, 204, 255));
        btnDelete.setText("Xóa");
        btnDelete.setBorder(null);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnDelete.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnDelete.setPreferredSize(new java.awt.Dimension(80, 40));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 82, -1));

        btnNew.setBackground(new java.awt.Color(204, 204, 255));
        btnNew.setText("Mới");
        btnNew.setBorder(null);
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnNew.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnNew.setPreferredSize(new java.awt.Dimension(80, 40));
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel1.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        btnAdd1.setBackground(new java.awt.Color(204, 204, 255));
        btnAdd1.setText("Thêm đơn hàng");
        btnAdd1.setBorder(null);
        btnAdd1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAdd1.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnAdd1.setPreferredSize(new java.awt.Dimension(80, 40));
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 180, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundform.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (checknull(new JTextField[]{txtMaKH, txtHoten, txtSDT})
                && checkloidinhdang(new JTextField[]{txtMaKH, txtHoten, txtSDT})) {
            int x = insert();
            if (x != 0) {
                loadData();
                btnAdd.setEnabled(false);
                checkNew();
                Dialog.ThongBao(this, "thanh cong");
            } else {
                Dialog.ThongBao(this, "that bai");
            }
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (checknull(new JTextField[]{txtMaKH, txtHoten, txtSDT})
                && checkloidinhdang(new JTextField[]{txtMaKH, txtHoten, txtSDT})) {
            int x = update();
            if (x != 0) {
                loadData();
                checkNew();
                Dialog.ThongBao(this, "thanh cong");
            } else {
                Dialog.ThongBao(this, "that bai");
            }
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKHMouseClicked
        // TODO add your handling code here:
        String makh = (String) tblKH.getValueAt(tblKH.getSelectedRow(), 0);
        Khachhang newkh = dao.find(makh);
        txtMaKH.setText(newkh.getMakh());
        txtHoten.setText(newkh.getHoten());
        cboGioitinh.setSelectedIndex(returnIdx(newkh.isGt()));
        txtSDT.setText(newkh.getSdt());
        txtDiachi.setText(newkh.getDiachi());
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
        btnAdd.setEnabled(false);
        txtMaKH.setEnabled(false);
    }//GEN-LAST:event_tblKHMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (Tienich.loggedAdmin() && checknull(new JTextField[]{txtMaKH})) {
            int x = delete();
            if (x != 0) {
                loadData();
                checkNew();
                Dialog.ThongBao(this, "thanh cong");
            } else {
                Dialog.ThongBao(this, "that bai");
            }
        } else {
            Dialog.ThongBao(this, "Quyền Admin");
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        checkNew();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        model = (DefaultTableModel) tblKH.getModel();
        model.setRowCount(0);
        for (Khachhang a : search()) {
            model.addRow(new Object[]{
                a.getMakh(),
                a.getHoten(),
                gioitinh(a.isGt()),
                a.getSdt(),
                a.getDiachi(),
                Tienich.FixNgayDK(a.getNgaydk())
            });
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        // TODO add your handling code here:
        String makh = txtMaKH.getText();
        if (makh.equals("")) {
            Dialog.ThongBao(this, "Bạn chưa chọn dữ liệu");
        } else {
            Tienich.khachhang = dao.find(makh);
            JDesktopPane forms = this.getDesktopPane();
            formADH form = new formADH();
            form.Fill(-1);
            form.loadSP(-1);
            this.dispose();
            forms.add(form);
            form.show();
        }
    }//GEN-LAST:event_btnAdd1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboGioitinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable tblKH;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setTen() {
        txtMaKH.setName("txtDiachi");
        txtHoten.setName("txtHoten");
        txtSDT.setName("txtManv");
    }

    @Override
    public boolean checknull(JTextField[] array) {
        for (JTextField field : array) {
            String text = field.getText();
            if (text.equals("")) {
                field.requestFocus();
                Dialog.ThongBao(this, "Không để trống!");
                return false;
            }
        }
        return true;
    }

    @Override
    public boolean checkloidinhdang(JTextField[] array) {
        setTen();
        dao.reLoad();
        String regexp = "([a-zA-Z\\u0080-\\u9fff]+\\s)+[a-zA-Z\\u0080-\\u9fff]+";
        String regexpPhone = "0[^0][0-9]{8}";
        for (JTextField field : array) {
            String text = field.getText();
            if (field.getName().equals("txtHoten")) {
                if (!text.matches(regexp)) {
                    field.requestFocus();
                    Dialog.ThongBao(this, "Không đúng định dạng!");
                    return false;
                }
            }
            if (field.getName().equals("txtSDT")) {
                if (!text.matches(regexpPhone)) {
                    field.requestFocus();
                    Dialog.ThongBao(this, "Số điện thoại không đúng định dạng");
                    return false;
                }
            }
            if (field.getName().equals("txtMaKH")) {
                if (text.contains(" ")) {
                    field.requestFocus();
                    Dialog.ThongBao(this, "Mã khách hàng không được có dấu cách");
                    return false;
                }
                if (dao.find(text)!=null) {
                    field.requestFocus();
                    Dialog.ThongBao(this, "Mã khách hàng không được trùng");
                    return false;
                }
            }
        }
        return true;
    }
}
