/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import DAO.Donhang;
import DAO.DonhangDAO;
import DAO.MySQL;
import Tools.Dialog;
import Tools.Tienich;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Chu Ai Duc
 */
public class formIdle extends javax.swing.JInternalFrame {

    /**
     * Creates new form formIdle
     */
    
    public formIdle() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        txtSearch.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        addDH = new javax.swing.JLabel();
        addKH = new javax.swing.JLabel();
        btnSearch = new javax.swing.JLabel();
        main = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSearch.setBackground(new java.awt.Color(51, 51, 51));
        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtSearch.setBorder(null);
        txtSearch.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 510, 40));

        addDH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addDHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addDHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addDHMouseExited(evt);
            }
        });
        jPanel1.add(addDH, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 240, 179, 238));

        addKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addKHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addKHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addKHMouseExited(evt);
            }
        });
        jPanel1.add(addKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 240, 179, 238));

        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 60, 60));

        main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formIdle.png"))); // NOI18N
        jPanel1.add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDHMouseEntered
        // TODO add your handling code here:
        addDH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_addDHMouseEntered

    private void addDHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDHMouseExited
        // TODO add your handling code here:
        addDH.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    }//GEN-LAST:event_addDHMouseExited

    private void addKHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addKHMouseEntered
        // TODO add your handling code here:
        addKH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_addKHMouseEntered

    private void addKHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addKHMouseExited
        // TODO add your handling code here:
        addKH.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    }//GEN-LAST:event_addKHMouseExited

    private void addKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addKHMouseClicked
        // TODO add your handling code here:
        if(Tienich.logged()){
            Tienich.label=4;
            JDesktopPane forms=this.getDesktopPane();
            formKH form=new formKH();
            this.dispose();
            forms.add(form);
            form.show();
        }
    }//GEN-LAST:event_addKHMouseClicked

    private void addDHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDHMouseClicked
        // TODO add your handling code here:
        if(Tienich.logged()){
            Tienich.label=4;
            formKH form=new formKH();
            JDesktopPane forms =this.getDesktopPane();
            this.dispose();
            forms.add(form);
            form.show();
            Dialog.ThongBao(this, "Chọn khách hàng");
        }else{
            Dialog.ThongBao(this,"Dang nhap di da");
        }
    }//GEN-LAST:event_addDHMouseClicked

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // TODO add your handling code here:
        try {
            DonhangDAO dao=new DonhangDAO();
            dao.reLoad();
            String tim=txtSearch.getText();
            ArrayList<Donhang> list = new ArrayList<>();
            String sql = "select donhang.MADH, khachhang.HOTEN from donhang join chitietdonhang on donhang.MADH=chitietdonhang.MADH join khachhang on donhang.MAKH=khachhang.MAKH where khachhang.HOTEN like '%"+tim+"%' or khachhang.sdt like '%"+tim+"%' or donhang.ngaydathang like '%" + tim + "%' group by donhang.MADH";
            ResultSet rs = MySQL.chaySelect(sql, (Object)null);
            while (rs.next()) {
                list.add(dao.find(rs.getInt("madh")));
            }
            JDesktopPane forms = this.getDesktopPane();
            System.out.println(list.size());
            formDH form=new formDH();
            form.themdulieu(list);
            System.out.println("da them thanh cong");
            this.dispose();
            forms.add(form);
            form.show();
            
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSearchMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addDH;
    private javax.swing.JLabel addKH;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel main;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
