/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import DAO.Nhanvien;
import DAO.NhanvienDAO;
import Tools.Dialog;
import Tools.Tienich;
import java.awt.Color;
import javax.swing.JDesktopPane;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Chu Ai Duc
 */
public class formlogin extends javax.swing.JInternalFrame implements Runnable {

    /**
     * Creates new form formlogin
     */
    Color transparent = new Color(0, 0, 0, 0);
    boolean click = true;
    NhanvienDAO daoNV = new NhanvienDAO();
    Thread t;
    public formlogin() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        txtUsername.setOpaque(false);
        txtPassword.setOpaque(false);
        password.setOpaque(false);
        txtPassword.setBackground(transparent);
        txtUsername.setBackground(transparent);
        password.setBackground(transparent);
        txtPassword.setVisible(false);
        daoNV.reLoad();
        
        t = new Thread(this);
        t.start();
    }

    public boolean kiemthu() {
        String username = txtUsername.getText().trim();
        if (username.equals("")) {
            Dialog.ThongBao(this, "Tên đăng nhập trống");
            return false;
        }
        String getpassword = "";
        if (txtPassword.isVisible()) {
            getpassword = txtPassword.getText();
        }
        if (password.isVisible()) {
            getpassword = new String(password.getPassword());
        }
        if (getpassword.equals("")) {
            Dialog.ThongBao(this, "Mật khẩu trống");
            return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        btnLogin = new javax.swing.JLabel();
        btnQR = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        btnToggle = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        panel.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 188, 41));

        btnQR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQRMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQRMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQRMouseExited(evt);
            }
        });
        panel.add(btnQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 188, 41));

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 204));
        txtUsername.setBorder(null);
        txtUsername.setCaretColor(new java.awt.Color(204, 255, 204));
        panel.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 270, 30));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 204));
        txtPassword.setBorder(null);
        txtPassword.setCaretColor(new java.awt.Color(204, 255, 204));
        panel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 302, 270, 30));

        password.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 204));
        password.setBorder(null);
        password.setCaretColor(new java.awt.Color(204, 255, 204));
        panel.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 302, 270, 30));

        btnToggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye1.png"))); // NOI18N
        btnToggle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnToggleMouseClicked(evt);
            }
        });
        panel.add(btnToggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 50, 30));

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formlogin.png"))); // NOI18N
        panel.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        // TODO add your handling code here:
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hoverlogin.png")));
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        // TODO add your handling code here:
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formlogin.png")));
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnToggleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnToggleMouseClicked
        // TODO add your handling code here:
        if (click) {
            btnToggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye2.png")));
            click = false;
            txtPassword.setText(new String(password.getPassword()));
            txtPassword.setVisible(true);
            password.setVisible(false);
        } else {
            btnToggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye1.png")));
            click = true;
            password.setText(txtPassword.getText());
            txtPassword.setVisible(false);
            password.setVisible(true);
        }

    }//GEN-LAST:event_btnToggleMouseClicked

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
        daoNV.reLoad();
        if (kiemthu()) {
            String username = txtUsername.getText().trim();
            String getpassword = "";
            if (txtPassword.isVisible()) {
                getpassword = txtPassword.getText();
            }
            if (password.isVisible()) {
                getpassword = new String(password.getPassword());
            }
            Nhanvien newnv = daoNV.find(username);
            if (newnv == null) {
                Dialog.ThongBao(this, "Tên đăng nhập không tồn tại");
            } else {
                if (newnv.getMatkhau().equals(getpassword)) {
                    Tienich.user = newnv;
                    Tienich.check = true;
                } else {
                    Dialog.ThongBao(this, "Mật khẩu không chính xác");
                }
            }
        }

    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnQRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQRMouseClicked
        // TODO add your handling code here:
        QRCam a = new QRCam();
        a.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        a.setLocationRelativeTo(null);
        a.setVisible(true);
    }//GEN-LAST:event_btnQRMouseClicked

    private void btnQRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQRMouseEntered
        // TODO add your handling code here:
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hoverQR.png")));
    }//GEN-LAST:event_btnQRMouseEntered

    private void btnQRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQRMouseExited
        // TODO add your handling code here:
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formlogin.png")));
    }//GEN-LAST:event_btnQRMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnLogin;
    private javax.swing.JLabel btnQR;
    private javax.swing.JLabel btnToggle;
    private javax.swing.JLabel menu;
    private javax.swing.JPanel panel;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {
            try {
                System.out.println("Running");
                if (Tienich.check) {
                    System.out.println("OK");
                    JDesktopPane forms = this.getDesktopPane();
                    formIdle form = new formIdle();
                    this.dispose();
                    forms.add(form);
                    form.show();
                    Dialog.ThongBao(this, "Đăng nhập thành công");
                    if (Tienich.user.getMatkhau().equals("0000")) {
                        Dialog.ThongBao(this, "Mật khẩu của bạn vừa được Reset, hãy đổi mật khẩu mới");
                    }
                    break;
                }
                Thread.sleep(500);
            } catch (Exception ex) {
                System.out.println(ex);
            }
        }
    }

}
