/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import DAO.DonhangDAO;
import DAO.Khachhang;
import DAO.KhachhangDAO;
import DAO.MySQL;
import DAO.NhacungcapDAO;
import Tools.Dialog;
import Tools.PrintChart;
import Tools.Tienich;
import com.itextpdf.text.pdf.codec.Base64;
import java.awt.Color;
import java.awt.Font;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.sql.ResultSet;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

import java.util.Date;
import java.util.Locale;
import javax.imageio.ImageIO;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Chu Ai Duc
 */
public class formTK extends javax.swing.JInternalFrame {

    /**
     * Creates new form formTK
     */
    Locale localeVN = new Locale("vi", "VN");
    NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);
    DefaultTableModel model;
    DefaultTableModel model1;
    DefaultTableModel model2;
    DefaultTableModel model3;
    DefaultTableModel model4;
    KhachhangDAO daokh = new KhachhangDAO();
    DonhangDAO daodh = new DonhangDAO();
    JFreeChart chartprint;
    SimpleDateFormat formatter1 = new SimpleDateFormat("dd-MM-yyyy");

    public formTK() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        tblTKHD.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tblTKHD.getTableHeader().setOpaque(false);
        tblTKHD.getTableHeader().setBackground(new java.awt.Color(32, 136, 203));
        tblTKHD.getTableHeader().setForeground(new java.awt.Color(255, 255, 255));
        tblTKSP.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tblTKSP.getTableHeader().setOpaque(false);
        tblTKSP.getTableHeader().setBackground(new java.awt.Color(32, 136, 203));
        tblTKSP.getTableHeader().setForeground(new java.awt.Color(255, 255, 255));
        tbldoanhthuDM.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tbldoanhthuDM.getTableHeader().setOpaque(false);
        tbldoanhthuDM.getTableHeader().setBackground(new java.awt.Color(32, 136, 203));
        tbldoanhthuDM.getTableHeader().setForeground(new java.awt.Color(255, 255, 255));
        tbldoanhthuYear.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tbldoanhthuYear.getTableHeader().setOpaque(false);
        tbldoanhthuYear.getTableHeader().setBackground(new java.awt.Color(32, 136, 203));
        tbldoanhthuYear.getTableHeader().setForeground(new java.awt.Color(255, 255, 255));
        tblTKKH.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tblTKKH.getTableHeader().setOpaque(false);
        tblTKKH.getTableHeader().setBackground(new java.awt.Color(32, 136, 203));
        tblTKKH.getTableHeader().setForeground(new java.awt.Color(255, 255, 255));
        loadCombox();
        btnPrint.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void loadCombox() {
        try {
            String sql = "select year(ngaydathang) from donhang group by year(ngaydathang) order by year(ngaydathang)";
            ResultSet rs = MySQL.chaySelect(sql, (Object) null);
            while (rs.next()) {
                cboYear.addItem(rs.getInt(1) + "");
            }
        } catch (Exception e) {
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblTKSP = new javax.swing.JTable();
        txtDay5 = new com.toedter.calendar.JDateChooser();
        txtDay6 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnGetSP = new javax.swing.JButton();
        countsl = new javax.swing.JLabel();
        countdt = new javax.swing.JLabel();
        cboSort1 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTKHD = new javax.swing.JTable();
        txtDay3 = new com.toedter.calendar.JDateChooser();
        txtDay4 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnGetHD = new javax.swing.JButton();
        cboSort = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtDay7 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        txtDay8 = new com.toedter.calendar.JDateChooser();
        btnGetKH = new javax.swing.JButton();
        cboSort2 = new javax.swing.JComboBox<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblTKKH = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        cboYear = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldoanhthuYear = new javax.swing.JTable();
        btnYear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtDay2 = new com.toedter.calendar.JDateChooser();
        txtDay1 = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbldoanhthuDM = new javax.swing.JTable();
        btnDM = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGetDoanhthu = new javax.swing.JButton();
        btnDM1 = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("BẢNG THỐNG KÊ CHUNG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        tblTKSP.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tblTKSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên SP", "Nhà cung cấp", "Số lượng", "Doanh thu"
            }
        ));
        tblTKSP.setFocusable(false);
        tblTKSP.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblTKSP.setRowHeight(30);
        tblTKSP.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tblTKSP.setShowVerticalLines(false);
        jScrollPane5.setViewportView(tblTKSP);
        if (tblTKSP.getColumnModel().getColumnCount() > 0) {
            tblTKSP.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblTKSP.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel7.setText("Từ ngày");

        jLabel8.setText("Đến ngày");

        btnGetSP.setText("Thống kê");
        btnGetSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetSPActionPerformed(evt);
            }
        });

        countsl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        countsl.setText("Tổng:");

        countdt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cboSort1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cboSort1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo số lượng", "Theo doanh thu" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGetSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDay5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(415, 415, 415)
                                .addComponent(cboSort1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(countsl, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(countdt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtDay6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(txtDay5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(cboSort1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGetSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(countsl)
                    .addComponent(countdt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sản phẩm", jPanel3);

        tblTKHD.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tblTKHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Ngày mua hàng", "Tên khách hàng", "Tổng tiền"
            }
        ));
        tblTKHD.setFocusable(false);
        tblTKHD.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblTKHD.setRowHeight(30);
        tblTKHD.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tblTKHD.setShowVerticalLines(false);
        jScrollPane4.setViewportView(tblTKHD);

        jLabel5.setText("Từ ngày");

        jLabel6.setText("Đến ngày");

        btnGetHD.setText("Thống kê");
        btnGetHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetHDActionPerformed(evt);
            }
        });

        cboSort.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cboSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo ngày tháng", "Theo giá trị đơn hàng" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGetHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDay3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(415, 415, 415)
                                .addComponent(cboSort, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtDay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(txtDay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGetHD, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(cboSort, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Đơn hàng", jPanel4);

        jLabel9.setText("Từ ngày");

        jLabel10.setText("Đến ngày");

        btnGetKH.setText("Thống kê");
        btnGetKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetKHActionPerformed(evt);
            }
        });

        cboSort2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cboSort2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Số lượng ", "Tien hang " }));

        tblTKKH.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tblTKKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Số lượng mua", "Tổng tiền hàng"
            }
        ));
        tblTKKH.setFocusable(false);
        tblTKKH.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblTKKH.setRowHeight(30);
        tblTKKH.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tblTKKH.setShowVerticalLines(false);
        jScrollPane6.setViewportView(tblTKKH);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap(57, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnGetKH, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboSort2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(jLabel9)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtDay7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel10)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtDay8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(495, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboSort2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetKH, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDay8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(txtDay7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addGap(440, 440, 440)))
        );

        jTabbedPane1.addTab("Khách hàng", jPanel6);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboYearActionPerformed(evt);
            }
        });
        jPanel2.add(cboYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 17, 306, -1));

        tbldoanhthuYear.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tbldoanhthuYear.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tháng", "Doanh thu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbldoanhthuYear.setFocusable(false);
        tbldoanhthuYear.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbldoanhthuYear.setRowHeight(30);
        tbldoanhthuYear.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tbldoanhthuYear.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tbldoanhthuYear);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 94, 362, 326));

        btnYear.setText("Biểu đồ năm");
        btnYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYearActionPerformed(evt);
            }
        });
        jPanel2.add(btnYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, -1));

        jLabel2.setText("Years:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 21, -1, -1));
        jPanel2.add(txtDay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, -1));
        jPanel2.add(txtDay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 17, -1, -1));

        tbldoanhthuDM.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tbldoanhthuDM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ngày/tháng", "Doanh thu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbldoanhthuDM.setFocusable(false);
        tbldoanhthuDM.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbldoanhthuDM.setRowHeight(30);
        tbldoanhthuDM.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tbldoanhthuDM.setShowVerticalLines(false);
        jScrollPane2.setViewportView(tbldoanhthuDM);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 362, 326));

        btnDM.setText("Biểu đồ");
        btnDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDMActionPerformed(evt);
            }
        });
        jPanel2.add(btnDM, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, -1, -1));

        jLabel3.setText("Từ ngày");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        jLabel4.setText("Đến ngày");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, -1));

        btnGetDoanhthu.setText("Thống kê");
        btnGetDoanhthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetDoanhthuActionPerformed(evt);
            }
        });
        jPanel2.add(btnGetDoanhthu, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 110, 30));

        btnDM1.setText("Biểu đồ tháng");
        btnDM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDM1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnDM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        btnPrint.setText("In biểu đồ");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, -1, -1));

        jTabbedPane1.addTab("Doanh thu", jPanel2);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 840, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboYearActionPerformed
        // TODO add your handling code here:
        try {
            model = (DefaultTableModel) tbldoanhthuYear.getModel();
            model.setRowCount(0);
            int year = Integer.parseInt(cboYear.getSelectedItem().toString());
            String sql = "call PROC_GETDOANHTHUNAM(?)";
            ResultSet rs = MySQL.chaySelect(sql, year);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt(1),
                    currencyVN.format(rs.getFloat(2))
                });
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_cboYearActionPerformed

    private void btnYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYearActionPerformed
        // TODO add your handling code here:
        DefaultCategoryDataset dod = new DefaultCategoryDataset();
        try {
            String sql = "select year(donhang.ngaydathang), sum(dongia*soluong) from donhang join chitietdonhang where donhang.madh=chitietdonhang.madh"
                    + " group by year(donhang.ngaydathang) order by year(donhang.ngaydathang)";
            ResultSet rs = MySQL.chaySelect(sql, (Object) null);
            while (rs.next()) {
                dod.setValue(rs.getFloat(2), "Doanhthu/Nam", rs.getInt(1) + "");
            }
            JFreeChart jchart = ChartFactory.createBarChart3D("Thong Ke Doanh Thu DTMILK", "Nam", "Doanh thu", dod, PlotOrientation.VERTICAL, false, true, true);

            CategoryPlot plot = jchart.getCategoryPlot();

            plot.setRangeGridlinePaint(Color.BLACK);

            ChartFrame chartFrm = new ChartFrame("Thong Ke", jchart, true);
            chartFrm.setVisible(true);
            chartFrm.setSize(1200, 600);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnYearActionPerformed

    private void btnDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDMActionPerformed
        // TODO add your handling code here:
        DefaultCategoryDataset dod = new DefaultCategoryDataset();
        try {
            Date d1 = txtDay1.getDate();
            Date d2 = txtDay2.getDate();
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            
            String sql = "select month(donhang.ngaydathang), sum(dongia*soluong) from donhang join chitietdonhang where donhang.madh=chitietdonhang.madh and donhang.NGAYDATHANG between ? and ? group by month(donhang.ngaydathang) order by month(donhang.ngaydathang)";
            ResultSet rs = MySQL.chaySelect(sql, d1, d2);
            while (rs.next()) {
                
                dod.setValue(rs.getFloat(2), "Doanhthu/Thang", rs.getInt(1) + "");
            }
            JFreeChart jchart = ChartFactory.createBarChart3D("Thong Ke Doanh Thu DTMILK", "Tu ngay: " + formatter.format(d1) + " den ngay " + formatter.format(d2), "Doanh thu", dod, PlotOrientation.VERTICAL, false, true, true);

            CategoryPlot plot = jchart.getCategoryPlot();
            
            plot.setRangeGridlinePaint(Color.BLACK);
            chartprint=jchart;
            btnPrint.setEnabled(true);
            ChartFrame chartFrm = new ChartFrame("Thong Ke", jchart, true);
            chartFrm.setVisible(true);
            chartFrm.setSize(1200, 600);

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnDMActionPerformed

    private void btnGetDoanhthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetDoanhthuActionPerformed
        try {
            model1 = (DefaultTableModel) tbldoanhthuDM.getModel();
            model1.setRowCount(0);
            Date d1 = txtDay1.getDate();
            Date d2 = txtDay2.getDate();
            String sql = "select donhang.ngaydathang, sum(dongia*soluong) from donhang join chitietdonhang where donhang.madh=chitietdonhang.madh and donhang.NGAYDATHANG between ? and ? group by donhang.ngaydathang order by donhang.ngaydathang";
            ResultSet rs = MySQL.chaySelect(sql, d1, d2);
            while (rs.next()) {
                model1.addRow(new Object[]{
                    Tienich.FixNgayDK(rs.getString(1)),
                    currencyVN.format(rs.getFloat(2))
                });
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnGetDoanhthuActionPerformed

    private void btnDM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDM1ActionPerformed
        // TODO add your handling code here:
        DefaultCategoryDataset dod = new DefaultCategoryDataset();
        try {
            int a = Integer.valueOf(cboYear.getSelectedItem().toString());
            String sql = "call PROC_GETDOANHTHUNAM(?)";
            ResultSet rs = MySQL.chaySelect(sql, a);

            while (rs.next()) {
                
                dod.setValue(rs.getFloat(2), "Doanhthu/Nam", rs.getInt(1) + "");

            }

            JFreeChart jchart = ChartFactory.createBarChart3D("Thong Ke Doanh Thu DTMILK", "Nam: " + cboYear.getSelectedItem(), "Doanh thu", dod, PlotOrientation.VERTICAL, false, true, true);

            CategoryPlot plot = jchart.getCategoryPlot();

            plot.setRangeGridlinePaint(Color.BLACK);

            ChartFrame chartFrm = new ChartFrame("Thong Ke", jchart, true);
            chartFrm.setVisible(true);
            chartFrm.setSize(1200, 600);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnDM1ActionPerformed

    private void btnGetHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetHDActionPerformed
        // TODO add your handling code here:
        try {
            daodh.reLoad();
            daokh.reLoad();
            model2 = (DefaultTableModel) tblTKHD.getModel();
            model2.setRowCount(0);
            Date d3 = txtDay3.getDate();
            Date d4 = txtDay4.getDate();
            ResultSet rs;
            String sql = "select donhang.madh,donhang.ngaydathang, sum(dongia*soluong) from donhang join chitietdonhang "
                    + "on donhang.madh=chitietdonhang.madh "
                    + "where donhang.NGAYDATHANG between ? and ? group by donhang.madh order by donhang.ngaydathang desc";
            String sql1 = "select donhang.madh,donhang.ngaydathang, sum(dongia*soluong) from donhang join chitietdonhang "
                    + "on donhang.madh=chitietdonhang.madh "
                    + "where donhang.NGAYDATHANG between ? and ? group by donhang.madh order by sum(dongia*soluong) desc";
            if (cboSort.getSelectedIndex() == 0) {
                rs = MySQL.chaySelect(sql, d3, d4);
            } else {
                rs = MySQL.chaySelect(sql1, d3, d4);
            }

            while (rs.next()) {
                model2.addRow(new Object[]{
                    rs.getInt(1),
                    Tienich.FixNgayDK(rs.getString(2)),
                    daokh.find(daodh.find(rs.getString(1)).getMakh()).getHoten(),
                    Tienich.currencyVN.format(rs.getFloat(3))
                });
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnGetHDActionPerformed

    private void btnGetSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetSPActionPerformed
        // TODO add your handling code here:
        try {
            NhacungcapDAO daoncc=new NhacungcapDAO();
            daoncc.reLoad();
            model3 = (DefaultTableModel) tblTKSP.getModel();
            model3.setRowCount(0);
            Date d5 = txtDay5.getDate();
            Date d6 = txtDay6.getDate();
            ResultSet rs;
            String sql = "select sanpham.masp,sanpham.tensp,sanpham.MANCC, sum(chitietdonhang.SOLUONG), sum(sanpham.dongia*chitietdonhang.soluong) from sanpham join chitietdonhang on sanpham.MASP=chitietdonhang.MASP  join donhang on chitietdonhang.madh=donhang.madh where ngaydathang between ? and ? group by sanpham.masp order by sum(chitietdonhang.SOLUONG) desc";
            String sql1 = "select sanpham.masp,sanpham.tensp,sanpham.MANCC, sum(chitietdonhang.SOLUONG), sum(sanpham.dongia*chitietdonhang.soluong) from sanpham join chitietdonhang on sanpham.MASP=chitietdonhang.MASP  join donhang on chitietdonhang.madh=donhang.madh where ngaydathang between ? and ? group by sanpham.masp order by sum(chitietdonhang.SOLUONG*chitietdonhang.DONGIA) desc";
            if (cboSort1.getSelectedIndex() == 0) {
                rs = MySQL.chaySelect(sql, d5, d6);
            } else {
                rs = MySQL.chaySelect(sql1, d5, d6);
            }

            ArrayList<Float> ds = new ArrayList<>();
            while (rs.next()) {
                model3.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    daoncc.find(rs.getString(3)).getTenncc(),
                    rs.getInt(4),
                    Tienich.currencyVN.format(rs.getFloat(5))
                });
                ds.add(rs.getFloat(5));
            }

            int count = 0;
            double doanhthu = 0;
            for (int i = 0; i < tblTKSP.getRowCount() - 1; i++) {
                count += Integer.valueOf(tblTKSP.getValueAt(i, 3).toString());
                doanhthu += ds.get(i);
            }
            countsl.setText("Tổng: " + count);
            countdt.setText(Tienich.currencyVN.format(doanhthu));
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnGetSPActionPerformed

    private void btnGetKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetKHActionPerformed
        // TODO add your handling code here:
        try {
        daokh.reLoad();
        model4 = (DefaultTableModel) tblTKKH.getModel();
        model4.setRowCount(0);
        Date d7 = txtDay7.getDate();
        Date d8 = txtDay8.getDate();
        ResultSet rs;
        String sql="select makh, sum(SOLUONG),sum(soluong*dongia) from donhang join chitietdonhang on donhang.MADH=chitietdonhang.MADH where donhang.NGAYDATHANG between ? and ? group by makh order by sum(soluong) desc";
        String sql1 ="select makh,sum(soluong), sum(SOLUONG*dongia) from donhang join chitietdonhang on donhang.MADH=chitietdonhang.MADH where donhang.NGAYDATHANG between ? and ? group by makh order by sum(soluong*dongia) desc;";
        if (cboSort2.getSelectedIndex() == 0) {
                rs = MySQL.chaySelect(sql, d7, d8);
            } else {
                rs = MySQL.chaySelect(sql1, d7, d8);
            }
            while (rs.next()) {
                model4.addRow(new Object[]{
                    rs.getString(1),
                    daokh.find(rs.getString(1)).getHoten(),
                    rs.getInt(2),
                    Tienich.currencyVN.format(rs.getFloat(3))
                });
            }
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_btnGetKHActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        Date d1 = txtDay1.getDate();
        Date d2 = txtDay2.getDate();
        new PrintChart().printChart(chartprint, formatter1.format(d1)+" den ngay "+ formatter1.format(d2));
        Dialog.ThongBao(this, "Đã in: "+formatter1.format(d1)+" đến ngày "+ formatter1.format(d2));
    }//GEN-LAST:event_btnPrintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDM;
    private javax.swing.JButton btnDM1;
    private javax.swing.JButton btnGetDoanhthu;
    private javax.swing.JButton btnGetHD;
    private javax.swing.JButton btnGetKH;
    private javax.swing.JButton btnGetSP;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnYear;
    private javax.swing.JComboBox<String> cboSort;
    private javax.swing.JComboBox<String> cboSort1;
    private javax.swing.JComboBox<String> cboSort2;
    private javax.swing.JComboBox<String> cboYear;
    private javax.swing.JLabel countdt;
    private javax.swing.JLabel countsl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblTKHD;
    private javax.swing.JTable tblTKKH;
    private javax.swing.JTable tblTKSP;
    private javax.swing.JTable tbldoanhthuDM;
    private javax.swing.JTable tbldoanhthuYear;
    private com.toedter.calendar.JDateChooser txtDay1;
    private com.toedter.calendar.JDateChooser txtDay2;
    private com.toedter.calendar.JDateChooser txtDay3;
    private com.toedter.calendar.JDateChooser txtDay4;
    private com.toedter.calendar.JDateChooser txtDay5;
    private com.toedter.calendar.JDateChooser txtDay6;
    private com.toedter.calendar.JDateChooser txtDay7;
    private com.toedter.calendar.JDateChooser txtDay8;
    // End of variables declaration//GEN-END:variables
}
