/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;


import Tools.Dialog;
import Tools.Tienich;
import java.awt.Frame;
import java.awt.HeadlessException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;

/**
 *
 * @author Chu Ai Duc
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    int x, y;
    boolean check = true;
    
    
    public main(int x, int y, JLabel btnDH, JLabel btnExit, JLabel btnHome, JLabel btnKH, JLabel btnLogout, JLabel btnMini, JLabel btnNV, JLabel btnPExit, JLabel btnSP, JLabel btnSetting, JLabel btnTK, JLabel clock, JPanel formlamviec, JPanel formpopup, JDesktopPane forms, JLabel hoverDH, JLabel hoverHome, JLabel hoverKH, JLabel hoverNV, JLabel hoverSP, JLabel hoverSet, JLabel hoverTK, JLabel jLabel1, JPanel jPanel1, JSeparator jSeparator2, JLabel main, JLabel popup) throws HeadlessException {
        this.x = x;
        this.y = y;
        this.btnDH = btnDH;
        this.btnExit = btnExit;
        this.btnHome = btnHome;
        this.btnKH = btnKH;
        this.btnLogout = btnLogout;
        this.btnMini = btnMini;
        this.btnNV = btnNV;
        this.btnPExit = btnPExit;
        this.btnSP = btnSP;
        this.btnSetting = btnSetting;
        this.btnTK = btnTK;
        this.clock = clock;
        this.formlamviec = formlamviec;
        this.formpopup = formpopup;
        this.forms = forms;
        this.hoverDH = hoverDH;
        this.hoverHome = hoverHome;
        this.hoverKH = hoverKH;
        this.hoverNV = hoverNV;
        this.hoverSP = hoverSP;
        this.hoverSet = hoverSet;
        this.hoverTK = hoverTK;
        this.jLabel1 = jLabel1;
        this.jPanel1 = jPanel1;
        this.jSeparator2 = jSeparator2;
        this.main = main;
        this.popup = popup;
    }

    public main() {
        initComponents();
        formpopup.setVisible(false);
        
        new Thread() {
            @Override
            public void run() {
                //To change body of generated methods, choose Tools | Templates.
                while (true) {
                    try {
                        if(Tienich.label==4){
                            setHover(hoverKH, 4);
                        }
                        if(Tienich.label!=6){
                            formpopup.setVisible(false);
                            check=true;
                        }
                        if(Tienich.user!=null){
                            
                        }
                        if (Tienich.user != null && txtNV.getText().equals("")) {
                            if(!Tienich.user.isVaitro()){
                                txtNV.setText("Nhân viên: " + Tienich.user.getHoten());
                            }else{
                                txtNV.setText("Admin: " + Tienich.user.getHoten());
                            }
                        }

                        Calendar car = Calendar.getInstance();
                        SimpleDateFormat formatter = new SimpleDateFormat("hh:mm:ss a    dd/MM/yyyy");
                        clock.setText(formatter.format(car.getTime()));
                        Thread.sleep(1000);
                    } catch (Exception ex) {
                        System.out.println(ex);
                    }
                }
            }
        }.start();
        formlogin newform = new formlogin();
        forms.add(newform);
        newform.show();

//        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        formpopup = new javax.swing.JPanel();
        btnLogout = new javax.swing.JLabel();
        btnPExit = new javax.swing.JLabel();
        popup = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        formlamviec = new javax.swing.JPanel();
        forms = new javax.swing.JDesktopPane();
        jSeparator2 = new javax.swing.JSeparator();
        btnExit = new javax.swing.JLabel();
        btnMini = new javax.swing.JLabel();
        btnSetting = new javax.swing.JLabel();
        clock = new javax.swing.JLabel();
        btnHome = new javax.swing.JLabel();
        btnNV = new javax.swing.JLabel();
        btnSP = new javax.swing.JLabel();
        btnDH = new javax.swing.JLabel();
        btnKH = new javax.swing.JLabel();
        btnTK = new javax.swing.JLabel();
        hoverNV = new javax.swing.JLabel();
        hoverSP = new javax.swing.JLabel();
        hoverDH = new javax.swing.JLabel();
        hoverKH = new javax.swing.JLabel();
        hoverTK = new javax.swing.JLabel();
        hoverHome = new javax.swing.JLabel();
        hoverSet = new javax.swing.JLabel();
        txtNV = new javax.swing.JLabel();
        main = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formpopup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        formpopup.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 70));

        btnPExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPExitMouseExited(evt);
            }
        });
        formpopup.add(btnPExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 280, 70));

        popup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/popup.png"))); // NOI18N
        formpopup.add(popup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 140));

        jPanel1.add(formpopup, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 280, 140));

        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 40));

        formlamviec.setBackground(new java.awt.Color(0, 0, 0));

        forms.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout formsLayout = new javax.swing.GroupLayout(forms);
        forms.setLayout(formsLayout);
        formsLayout.setHorizontalGroup(
            formsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        formsLayout.setVerticalGroup(
            formsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout formlamviecLayout = new javax.swing.GroupLayout(formlamviec);
        formlamviec.setLayout(formlamviecLayout);
        formlamviecLayout.setHorizontalGroup(
            formlamviecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formlamviecLayout.createSequentialGroup()
                .addComponent(forms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        formlamviecLayout.setVerticalGroup(
            formlamviecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formlamviecLayout.createSequentialGroup()
                .addComponent(forms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(formlamviec, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 40, 860, 560));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 1, 490));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1145, 0, 55, 40));

        btnMini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mini.png"))); // NOI18N
        btnMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMiniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMiniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMiniMouseExited(evt);
            }
        });
        jPanel1.add(btnMini, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 55, 40));

        btnSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnSet.png"))); // NOI18N
        btnSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSettingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSettingMouseExited(evt);
            }
        });
        jPanel1.add(btnSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 573, 61, 61));

        clock.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        clock.setForeground(new java.awt.Color(255, 255, 255));
        clock.setText("Clock");
        jPanel1.add(clock, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 615, 210, -1));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnHome.png"))); // NOI18N
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 128, 331, 65));

        btnNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnNV.png"))); // NOI18N
        btnNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNVMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNVMouseExited(evt);
            }
        });
        jPanel1.add(btnNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 331, 65));

        btnSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnSP.png"))); // NOI18N
        btnSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSPMouseExited(evt);
            }
        });
        jPanel1.add(btnSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 277, 331, 65));

        btnDH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnDH.png"))); // NOI18N
        btnDH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDHMouseExited(evt);
            }
        });
        jPanel1.add(btnDH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 344, 331, 65));

        btnKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnKH.png"))); // NOI18N
        btnKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKHMouseExited(evt);
            }
        });
        jPanel1.add(btnKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 411, 331, 65));

        btnTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnTK.png"))); // NOI18N
        btnTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTKMouseExited(evt);
            }
        });
        jPanel1.add(btnTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 478, 331, 65));

        hoverNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnNV.png"))); // NOI18N
        jPanel1.add(hoverNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 331, 65));

        hoverSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnSP.png"))); // NOI18N
        jPanel1.add(hoverSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 277, 331, 65));

        hoverDH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnDH.png"))); // NOI18N
        jPanel1.add(hoverDH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 344, 331, 65));

        hoverKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnKH.png"))); // NOI18N
        jPanel1.add(hoverKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 411, 331, 65));

        hoverTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnTK.png"))); // NOI18N
        jPanel1.add(hoverTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 478, 331, 65));

        hoverHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnHome.png"))); // NOI18N
        jPanel1.add(hoverHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 128, 331, 65));

        hoverSet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnSet.png"))); // NOI18N
        jPanel1.add(hoverSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 573, 61, 61));

        txtNV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtNV.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 615, -1, -1));

        main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/main.png"))); // NOI18N
        main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainMouseClicked(evt);
            }
        });
        jPanel1.add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 650));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        // TODO add your handling code here:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void btnMiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMiniMouseClicked
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_btnMiniMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        if (Dialog.XacNhan(this, "Bạn chắc chắn muốn thoát?")) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnMiniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMiniMouseEntered
        // TODO add your handling code here:
        btnMini.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_btnMiniMouseEntered

    private void btnMiniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMiniMouseExited
        // TODO add your handling code here:
        btnMini.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    }//GEN-LAST:event_btnMiniMouseExited

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnSettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingMouseEntered
        // TODO add your handling code here:
        hoverSet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hoverSet.png")));
    }//GEN-LAST:event_btnSettingMouseEntered

    private void btnSettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingMouseExited
        // TODO add your handling code here:
        if (Tienich.label!=6) {
            hoverSet.setIcon(null);
        }

    }//GEN-LAST:event_btnSettingMouseExited

    private void btnSPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSPMouseEntered
        // TODO add your handling code here:
        hoverSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hover.png")));

    }//GEN-LAST:event_btnSPMouseEntered

    private void btnSPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSPMouseExited
        // TODO add your handling code here:
        if (Tienich.label!=2) {
            hoverSP.setIcon(null);
        }
    }//GEN-LAST:event_btnSPMouseExited

    private void btnSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSPMouseClicked
        // TODO add your handling code here:
        if (Tienich.logged()) {
            formSP form = new formSP();
            forms.removeAll();
            forms.add(form);
            form.show();
            setHover(hoverSP,2);
        } else {
            Dialog.ThongBao(this, "Bạn hãy đăng nhập");
        }

    }//GEN-LAST:event_btnSPMouseClicked

    private void btnDHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDHMouseClicked
        // TODO add your handling code here:
        if (Tienich.logged()) {
            formDH form = new formDH();
            forms.removeAll();
            forms.add(form);
            form.show();
            setHover(hoverDH,3);
        } else {
            Dialog.ThongBao(this, "Bạn hãy đăng nhập");
        }
    }//GEN-LAST:event_btnDHMouseClicked

    private void btnDHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDHMouseEntered
        // TODO add your handling code here:
        hoverDH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hover.png")));
    }//GEN-LAST:event_btnDHMouseEntered

    private void btnDHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDHMouseExited
        // TODO add your handling code here:
        if (Tienich.label!=3) {
            hoverDH.setIcon(null);
        }
    }//GEN-LAST:event_btnDHMouseExited

    private void btnKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKHMouseClicked
        // TODO add your handling code here:
        if (Tienich.logged()) {
            formKH form = new formKH();
            forms.removeAll();
            forms.add(form);
            form.show();
            setHover(hoverKH,4);
        } else {
            Dialog.ThongBao(this, "Bạn hãy đăng nhập");
        }
    }//GEN-LAST:event_btnKHMouseClicked

    private void btnKHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKHMouseEntered
        // TODO add your handling code here:
        hoverKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hover.png")));
    }//GEN-LAST:event_btnKHMouseEntered

    private void btnKHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKHMouseExited
        // TODO add your handling code here:
        if (Tienich.label!=4) {
            hoverKH.setIcon(null);
        }
    }//GEN-LAST:event_btnKHMouseExited

    private void btnTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTKMouseClicked
        // TODO add your handling code here:
        if (Tienich.loggedAdmin()) {
            formTK form = new formTK();
            forms.removeAll();
            forms.add(form);
            form.show();
            setHover(hoverTK,5);
        } else {
            Dialog.ThongBao(this, "Quyền Admin!");
        }
        
    }//GEN-LAST:event_btnTKMouseClicked

    private void btnTKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTKMouseEntered
        // TODO add your handling code here:
        hoverTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hover.png")));
    }//GEN-LAST:event_btnTKMouseEntered

    private void btnTKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTKMouseExited
        // TODO add your handling code here:
        if (Tienich.label!=5) {
            hoverTK.setIcon(null);
        }
    }//GEN-LAST:event_btnTKMouseExited

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        if (Tienich.logged()) {
            formIdle form = new formIdle();
            forms.removeAll();
            forms.add(form);
            form.show();
            setHover(hoverHome, 0);
        } else {
            Dialog.ThongBao(this, "Bạn hãy đăng nhập");
        }
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        // TODO add your handling code here:
        hoverHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hoverHome.png")));
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        // TODO add your handling code here:
        if(Tienich.label!=0)hoverHome.setIcon(null);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNVMouseClicked
        // TODO add your handling code here:

        if (Tienich.loggedAdmin()) {
            formNV form = new formNV();
            forms.removeAll();
            forms.add(form);
            form.show();
            setHover(hoverNV,1);
        } else if (Tienich.logged()) {
            formInfo form = new formInfo();
            forms.removeAll();
            forms.add(form);
            form.show();
            setHover(hoverNV,1);
        } else {
            Dialog.ThongBao(this, "Bạn hãy đăng nhập");
        }

    }//GEN-LAST:event_btnNVMouseClicked

    private void btnNVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNVMouseEntered
        // TODO add your handling code here:
        hoverNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hover.png")));
    }//GEN-LAST:event_btnNVMouseEntered

    private void btnNVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNVMouseExited
        // TODO add your handling code here:
        if (Tienich.label!=1) {
            hoverNV.setIcon(null);
        }

    }//GEN-LAST:event_btnNVMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        for (double i = 0.0; i < 1.0; i += 0.1) {
            String val = "" + i;
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(40);
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        popup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hoverLogout.png")));

    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        popup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/popup.png")));
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnPExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPExitMouseEntered
        // TODO add your handling code here:
        popup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hoverpopExit.png")));
    }//GEN-LAST:event_btnPExitMouseEntered

    private void btnPExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPExitMouseExited
        // TODO add your handling code here:
        popup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/popup.png")));
    }//GEN-LAST:event_btnPExitMouseExited

    private void btnSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingMouseClicked
        // TODO add your handling code here:

        if (check) {
            Tienich.label = 6;
            setHover(hoverSet,6);
            formpopup.setVisible(true);
            check = false;
        } else {
            hoverSet.setIcon(null);
            formpopup.setVisible(false);
            check = true;
            Tienich.label = -1;
        }
    }//GEN-LAST:event_btnSettingMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        if (Tienich.user == null) {
            hoverSet.setIcon(null);
            formpopup.setVisible(false);
            check = true;
            Tienich.label = -1;
            Dialog.ThongBao(this, "Bạn chưa đăng nhập");

        } else {
            txtNV.setText("");
            hoverSet.setIcon(null);
            formpopup.setVisible(false);
            check = true;
            Tienich.label = -1;
            Tienich.user = null;
            Tienich.check = false;
            forms.removeAll();
            formlogin newform = new formlogin();
            forms.add(newform);
            newform.show();
            Dialog.ThongBao(this, "Đã đăng xuất");
        }


    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnPExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPExitMouseClicked
        // TODO add your handling code here:
        if (Dialog.XacNhan(this, "Bạn chắc chắn muốn thoát?")) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnPExitMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:v
    }//GEN-LAST:event_jPanel1MouseClicked

    private void mainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMouseClicked
        // TODO add your handling code here:
        formpopup.setVisible(false);
        hoverSet.setIcon(null);
        check = true;
    }//GEN-LAST:event_mainMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    public void setHover(javax.swing.JLabel ten,int x) {
        if (ten != null) {
            
            Tienich.label = x;
            hoverDH.setIcon(null);
            hoverHome.setIcon(null);
            hoverKH.setIcon(null);
            hoverNV.setIcon(null);
            hoverSP.setIcon(null);
            hoverSet.setIcon(null);
            hoverTK.setIcon(null);
            if(ten==hoverHome){
                hoverHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hoverHome.png")));
            }else if(ten==hoverSet){
                ten.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hoverSet.png")));
            }else{
                ten.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hover.png")));
            }
            
        }else{
            Tienich.label = x;
            hoverDH.setIcon(null);
            hoverHome.setIcon(null);
            hoverKH.setIcon(null);
            hoverNV.setIcon(null);
            hoverSP.setIcon(null);
            hoverSet.setIcon(null);
            hoverTK.setIcon(null);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDH;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnKH;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnMini;
    private javax.swing.JLabel btnNV;
    private javax.swing.JLabel btnPExit;
    private javax.swing.JLabel btnSP;
    private javax.swing.JLabel btnSetting;
    private javax.swing.JLabel btnTK;
    private javax.swing.JLabel clock;
    private javax.swing.JPanel formlamviec;
    private javax.swing.JPanel formpopup;
    private javax.swing.JDesktopPane forms;
    private javax.swing.JLabel hoverDH;
    private javax.swing.JLabel hoverHome;
    private javax.swing.JLabel hoverKH;
    private javax.swing.JLabel hoverNV;
    private javax.swing.JLabel hoverSP;
    private javax.swing.JLabel hoverSet;
    private javax.swing.JLabel hoverTK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel main;
    private javax.swing.JLabel popup;
    private javax.swing.JLabel txtNV;
    // End of variables declaration//GEN-END:variables

}
